version: "2"
services:
  # envoy -> haproxy reverse proxy -> podinfo
  envoy-haproxy:
    build: .
    entrypoint: /usr/local/bin/envoy
    command:
      - -c
      - /conf/config.yaml
      - --log-level
      - info
      - --service-cluster
      - envoy
      - --service-node
      - envoy
    container_name: envoy-haproxy
    expose:
      - "80"
      - "9901"
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.3
    restart: always
    volumes:
      - ./envoy-haproxy.yaml:/conf/config.yaml
  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    restart: always
    ports:
      - "80"
      - "1936"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.4

  # envoy -> podinfo
  envoy-direct:
    build: .
    entrypoint: /usr/local/bin/envoy
    command:
      - -c
      - /conf/config.yaml
      - --log-level
      - info
      - --service-cluster
      - envoy
      - --service-node
      - envoy
    expose:
      - "80"
      - "9901"
    container_name: envoy-direct
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.6
    restart: always
    volumes:
      - ./envoy-direct.yaml:/conf/config.yaml

  # monitoring tooling
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - "9090"
    restart: unless-stopped
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.20
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.21
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  # podinfo web application
  podinfo:
    expose:
      - "9898"
    container_name: podinfo
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.100
    restart: always
    image: stefanprodan/podinfo

  # nginx web server
  nginx:
    image: nginx:latest
    container_name: nginx
    expose:
      - "80"
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.110

  # apache2 web server
  apache2:
    image: httpd:latest
    container_name: apache2
    expose:
      - "80"
    networks:
      envoy-http-proxy:
        ipv4_address: 172.19.0.120

networks:
  envoy-http-proxy:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1

volumes:
  prom_data:
