{
 "title": "Envoy Clusters",
 "description": "Envoy proxy monitoring Dashboard with cluster and service level templates. ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(envoy_server_uptime,instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Upstream",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{instance=~\"$instance\"},envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{instance=~\"$instance\",envoy_cluster_name=~\"$cluster\"})  - sum(envoy_cluster_membership_total{instance=~\"$instance\",envoy_cluster_name=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{instance=~\"$instance\",envoy_cluster_name=~\"$cluster\"})-sum(envoy_cluster_membership_healthy{instance=~\"$instance\",envoy_cluster_name=~\"$cluster\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Downstream Total active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream active connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{instance=~\"$instance\",envoy_cluster_name=~\"$cluster\"}) by (instance, envoy_cluster_name)",
     "legendFormat": "({{instance}}) {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Downstream Total active requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Total requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{instance=~\"$instance\",envoy_cluster_name=~\"$cluster\"}[1m])) by (instance, envoy_cluster_name)",
     "legendFormat": "({{instance}}) {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "{{service}} - in"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{instance=~\"$instance\"}[1m])) by (service)",
     "legendFormat": "{{service}} - out"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$cluster\",instance=~\"$instance\"}[1m])) by (instance,envoy_cluster_name)",
     "legendFormat": "({{instance}}) {{envoy_cluster_name}} - in"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$cluster\",instance=~\"$instance\"}[1m])) by (instance,envoy_cluster_name)",
     "legendFormat": "({{instance}}) {{envoy_cluster_name}} - out"
    }
   ]
  },
  {
   "title": "Downstream HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, envoy_cluster_name, envoy_response_code_class)\n(irate(envoy_listener_http_downstream_rq_xx{envoy_http_conn_manager_prefix!=\"admin\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "({{instance}}) {{envoy_cluster_name}} {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Upstream HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, envoy_cluster_name, envoy_response_code_class)\n(irate(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$cluster\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "({{instance}}) {{envoy_cluster_name}} {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "OWASP Coraza WAF Interruptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, phase, rule_id)\n(irate(waf_filter_tx_interruptions{instance=~\"$instance\"}[5m]))",
     "legendFormat": "({{instance}}) {{phase}} {{rule_id}}"
    }
   ]
  },
  {
   "title": "OWASP Coraza WAF Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)\n(irate(waf_filter_tx_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "({{instance}}) {{phase}} {{rule_id}}"
    }
   ]
  }
 ]
}